### ISSUE TITLE
Elementor editor-generated code has syntax error

### ISSUE THREAD

**Issue by vasomanager** [elementor/hello-theme-child#36] opened 2022-09-13 19:38 UTC
Hi guys, I'm creating an account just to try and fix this problem.

I'm using QuicCloud CDN's Page Optimization feature and the system have encountered one UCSS errors throughout a variety of pages within my WordPress page (running the latest version of Elementor and using Hello Elementor theme). Here's the error message:

unable to parse undefined:\n<css input>:1:98249: Missed semicolon\n\t1:     -> :1em;opacity:.9;line-height:.75,padding:\n\t2:        pector>.ab-item:before{content:\"\\f348\";t\n\t3:        \n\t4:        \n\t5:         * Font Awesome Free 5.15.3 by @fontawesome - https://fontawesome.com/\n\t6:         * License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)\n

I've looked into my custom added CSS codes and concluded that the problem must lie in Elementor's CSS code. Just unsure about how to fix this error so it doesn't eat up valuable CPU usage. Thank you!

**Comment by rami-elementor** [comment] 2023-04-29 10:41
Closing this issue.

Please contact QuicCloud CDN's support, looks like Page Optimization feature issue.

No evidence the issue is in Hello Theme.

**Closed by rami-elementor** 2023-04-29 10:41 UTC
